### ISSUE TITLE
 bitcode-enabled Applications fail to archive (2.0.0-beta4)

### ISSUE THREAD

**Issue by hieplebstar** [twilio/cocoapod-specs#40]
Hi, Please help...
Error from Xcode 8
ld: bitcode bundle could not be generated because '/Volumes/Work/XXXX/XXXX/XXXX/Pods/TwilioVoiceClient/TwilioVoiceClient.framework/TwilioVoiceClient' was built without full bitcode. All frameworks and dylibs for bitcode must be generated from Xcode Archive or Install build for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by bchen-twilio** [comment]
Hi @hieplebstar,
Bobie here from the iOS Voice team.
We've also noticed this issue and we've resolved it and the fix will be included in the next beta.
Sorry for the inconvenience but for the time being could you disable bitcode in your app until the official release is out?
Or you could also try the patch if this issue is blocking your project.
https://drive.google.com/file/d/0B0jCXbOI9plrcmYzNFhRVF8tc0E/view?usp=sharing

Please let us know if this helps.
Thanks.

**Comment by leluhien** [comment]
Hi, iOS Voice tem
Thank you so much!

**Comment by hieplebstar** [comment]
Hi, iOS Voice team
Thank you so much!
