### ISSUE TITLE
Crash making calls

### ISSUE THREAD

**Issue by marioacarvalho** [twilio/cocoapod-specs#41]
Hi,

I'm having a strange call when I try to make a call. The crash is the following:

```
MyApplication twilio_pj_pool_alloc:
    0x100224780 <+0>:  ldr    x9, [x0, #88]
    0x100224784 <+4>:  tst    x1, #0x3
    0x100224788 <+8>:  add    x8, x1, #4                ; =4 
    0x10022478c <+12>: and    x8, x8, #0xfffffffffffffffc
    0x100224790 <+16>: csel   x10, x1, x8, eq
    0x100224794 <+20>: ldp    x8, x11, [x9, #24]
    0x100224798 <+24>: sub    x11, x11, x8
    0x10022479c <+28>: cmp    x11, x10
    0x1002247a0 <+32>: b.lo   0x1002247b8               ; <+56> at pool_i.h:62
    0x1002247a4 <+36>: add    x10, x8, x10
    0x1002247a8 <+40>: str    x10, [x9, #24]
    0x1002247ac <+44>: cbz    x8, 0x1002247b8           ; <+56> at pool_i.h:62
    0x1002247b0 <+48>: mov    x0, x8
    0x1002247b4 <+52>: ret    
    0x1002247b8 <+56>: b      0x1002247bc               ; twilio_pj_pool_allocate_find at pool.c:91
```

Any idea? 

I don't have any optimisation on code.

Thanks

_Added_

I'm using `TwilioClient` pod

**Comment by marioacarvalho** [comment]
Link to StackOverflow similar question [http://stackoverflow.com/questions/36541133/crashed-twilio-pj-pool-alloc?noredirect=1#comment68589581_36541133](SO)

**Comment by bchen-twilio** [comment]
Hi @marioacarvalho,
Bobie here from the iOS Voice SDK team. I am sorry that you are experiencing crashes when using the Client iOS SDK.
Since  has decided to drop VoIP socket support in iOS 9 and 10, we have pushed out the hew Programmable Voice iOS SDK which, instead of persistent registration, leverages 's VoIP Push Notification to provide a more reliable incoming capability.
Here is a very cool getting-started guide: https://www.twilio.com/docs/api/voice-sdk/ios/getting-started
A few things to keep in mind when migrating from TwilioClient to the TwilioVoiceClient iOS SDK:
- We are using the [Twilio Access Token](https://www.twilio.com/docs/api/rest/access-tokens), different from the classic Twilio Capability Token, to provide the account activity authentication. This requires you to use the latest Twilio server help libraries in order to generate the new token. You can also find the server implementation guide in the getting-started guide.
- The Voice SDK requires you to create an  VoIP Service Certificate, instead of using the regular APNS service.

Again we feel sorry for your inconvenience and it would be great if you could give the Programmable Voice iOS SDK a try and let us know if you run into any issue or any feedback/suggestion will be greatly appreciated!

Thanks.

**Comment by bchen-twilio** [comment]
Hi @marioacarvalho 

How are things? just want to see if you are still having the crash issue using the SDK.
We did see a couple of users having similar problem and managed to resolve it by adding the microphone privacy setting in the app's plist.
I am closing this ticket assuming that this is resolved.
Please feel free to reach out to the team and create issue in the following repositories in the future:
Obj-C:
https://github.com/twilio/voice-quickstart-objc
Swift:
https://github.com/twilio/voice-quickstart-swift

Cheers,
-bobie
